env:
  TERM: xterm-256color
window:
  padding:
    x: 5
    y: 5
  dynamic_padding: false
  opacity: 0.5
  decorations: none
  startup_mode: Maximized
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: dark
  opacity: 1.0
scrolling:
  history: 5000
font:
  normal:
    family: Unifont-JP
    style: Regular
  bold:
    family: Unifont-JP
    style: Bold
  italic:
    family: Unifont-JP
    style: Italic
  bold_italic:
    family: Unifont-JP
    style: Bold Italic
  size: 12
  offset:
    x: 0
    y: 1
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: "#282828"
    foreground: "#ebdbb2"
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"
key_bindings:
  - key: V
    mods: Control|Shift
    action: Paste
  - key: C
    mods: Control|Shift
    action: Copy
  - key: Insert
    mods: Shift
    action: PasteSelection
  - key: Key0
    mods: Control
    action: ResetFontSize
  - key: Equals
    mods: Control
    action: IncreaseFontSize
  - key: F11
    mods: None
    action: ToggleFullscreen
  - key: Paste
    mods: None
    action: Paste
  - key: Copy
    mods: None
    action: Copy
  - key: L
    mods: Control
    action: ClearLogNotice
  - key: L
    mods: Control
    chars: "\f"
  - key: PageUp
    mods: None
    action: ScrollPageUp
    mode: ~Alt
  - key: PageDown
    mods: None
    action: ScrollPageDown
    mode: ~Alt
  - key: Home
    mods: Shift
    action: ScrollToTop
    mode: ~Alt
  - key: End
    mods: Shift
    action: ScrollToBottom
    mode: ~Alt

